// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CompressData struct {
	Url string `json:"url"` // 优化后文件的Supabase URL
}

type ModelCompressRequest struct {
	InputUrl     string `json:"input_url" validate:"required,url"` // 输入模型URL
	TexSize      uint   `json:"tex_size" default:"1024"`           // 纹理尺寸
	RemoveNormal bool   `json:"remove_normal" default:"false"`     // 是否移除法线纹理
	ConvertKtx2  bool   `json:"convert_ktx2" default:"false"`      // 是否转换为KTX2
}

type ModelCompressResponse struct {
	Data    CompressData `json:"data"`    // 引用独立的 CompressData 结构体
	Error   *string      `json:"error"`   // 错误信息（成功时为null，用指针实现）
	Success bool         `json:"success"` // 成功标识（true/false）
}
